n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
j = "search_next"
k = "move_next_word_end"
l = "insert_mode"
J = "search_prev"
K = "move_next_long_word_end"
L = "insert_at_line_start"
"C-n" = "goto_next_diag"
"C-e" = "goto_prev_diag"
"S-h" = "swap_view_left"
"S-i" = "swap_view_right"
"S-n" = "swap_view_down"
"S-e" = "swap_view_up"
E = "hover"
